version: '3.8'

services:
  web:
    image: tabuddy_image:v2
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    dns:
      - 8.8.8.8
    container_name: tabuddy_wsgi
    working_dir: /TaBuddy
    command: /entrypoint.sh
    volumes:
      - ./TaBuddy:/TaBuddy
      - /raid/ganesh/nagakalyani/Downloads/CodeLlama-7b-Instruct-hf:/TaBuddy/models/CodeLlama
    ports:
      - "8002:8000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MODEL_DIRECTORY_PATH=/TaBuddy/models/CodeLlama
      - ADAPTER_PATH=/TaBuddy/adapters/CodeLlama/final_checkpoint
      - DEVICE=cuda:0
      - LOG_DIR=/TaBuddy/logs
    runtime: nvidia
    networks:
      - tabuddy_net

  celery:
    image: tabuddy_image:v2
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    dns:
      - 8.8.8.8
    container_name: tabuddy_celery
    working_dir: /TaBuddy
    command: celery -A TaBuddy worker --loglevel=info --pool=solo
    depends_on:
      - web
      - redis
    volumes:
      - ./TaBuddy:/TaBuddy
      - /raid/ganesh/nagakalyani/Downloads/CodeLlama-7b-Instruct-hf:/TaBuddy/models/CodeLlama
    environment:
      - DEVICE=cuda:0
      - MODEL_DIRECTORY_PATH=/TaBuddy/models/CodeLlama
      - ADAPTER_PATH=/TaBuddy/adapters/CodeLlama/final_checkpoint
      - LOG_DIR=/TaBuddy/logs

    runtime: nvidia
    networks:
      - tabuddy_net

  mongodb:
    image: mongo:7.0.14
    container_name: tabuddy_mongodb
    command: ["mongod", "--quiet", "--auth", "--bind_ip_all"]
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - tabuddy_net

  redis:
    image: redis
    container_name: tabuddy_redis
    ports:
      - "6379:6379"
    networks:
      - tabuddy_net

  mongo-express:
    image: mongo-express
    container_name: tabuddy_mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: tabuddy_mongodb
    depends_on:
      - mongodb
    networks:
      - tabuddy_net
  
  flower:
    image: tabuddy_image:v2
    container_name: tabuddy_flower
    working_dir: /TaBuddy
    volumes:
      - ./TaBuddy:/TaBuddy
    command: celery -A TaBuddy flower --port=5555 --broker=redis://redis:6379/0 
    ports:
      - "5556:5555"
    depends_on:
      - redis
      - celery
    networks:
      - tabuddy_net


networks:
  tabuddy_net:
    driver: bridge
