# Generated by Django 4.1.13 on 2025-04-19 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Default Criterion Title', max_length=255)),
                ('description', models.TextField(default='No description provided.')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('problem_statement', models.TextField(default='No problem statement provided.')),
                ('user_id', models.CharField(default='Unknown User ID', max_length=255)),
                ('lab_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(default='Unknown Student ID', max_length=255)),
                ('dummy_id', models.CharField(default='Unknown Dummy ID', max_length=255)),
                ('filename', models.CharField(default='default_filename.cpp', max_length=255)),
                ('source_code', models.TextField(default='No source code provided.')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposit_data.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Default Title', max_length=255)),
                ('description', models.TextField(default='No description provided.')),
                ('marks', models.IntegerField(default=0)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposit_data.criteria')),
            ],
        ),
        migrations.CreateModel(
            name='GradingHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manual_comments', models.TextField(default='No comments.')),
                ('ai_comments', models.TextField(default='No AI reasonings.')),
                ('ai_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_grading_histories', to='deposit_data.rating')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposit_data.criteria')),
                ('manual_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_grading_histories', to='deposit_data.rating')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposit_data.submission')),
            ],
        ),
        migrations.AddField(
            model_name='criteria',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposit_data.problem'),
        ),
    ]
